server:
    port: 10007
spring:
     datasource:
        url: jdbc:mysql://192.168.12.139/location?useUnicode=true&characterEncoding=utf8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        username: young
        password: young
     application:
             name: es-provider
    #集成SpringBoot-admin          
#    boot:
#       admin:
#           client:
#               url: http://localhost:10006
#集成 es
elasticsearch:
          port: 9300
          clustername: elasticsearch
          hosts:  192.168.12.139
mybatis:
     mapperLocations: classpath*:mappers/*Mapper.xml
     typeAliasesPackage: com.young.tkmappers.entity
     configuration:
              mapUnderscoreToCamelCase: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#management:
#     endpoints:
#            web:
#              exposure: 
#                  include: "*"
