#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.12.139/admins?useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: young
    password: young
#mybatis
mybatis:
     mapperLocations: classpath*:mappers/*Mapper.xml
     typeAliasesPackage: com.young.tkmappers.entity
     configuration:
              mapUnderscoreToCamelCase: true
#打印sql
logging:
   level:
     com.young.tkmappers.mapper: debug
#集成Tk
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true
#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql